2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Configure stats pid to 40448
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from C:\Users\OJH\.config\wandb\settings
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_104521-s57l13nj\logs\debug.log
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_104521-s57l13nj\logs\debug-internal.log
2024-03-05 10:45:21,419 INFO    MainThread:40448 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002959A30FD10>
2024-03-05 10:45:21,420 INFO    MainThread:40448 [wandb_init.py:init():566] calling init triggers
2024-03-05 10:45:21,420 INFO    MainThread:40448 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 10:45:21,420 INFO    MainThread:40448 [wandb_init.py:init():616] starting backend
2024-03-05 10:45:21,420 INFO    MainThread:40448 [wandb_init.py:init():620] setting up manager
2024-03-05 10:45:21,427 INFO    MainThread:40448 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 10:45:21,428 INFO    MainThread:40448 [wandb_init.py:init():628] backend started and connected
2024-03-05 10:45:21,438 INFO    MainThread:40448 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 10:45:21,438 INFO    MainThread:40448 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-05 10:45:21,438 INFO    MainThread:40448 [wandb_init.py:init():720] updated telemetry
2024-03-05 10:45:21,469 INFO    MainThread:40448 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 10:45:22,097 INFO    MainThread:40448 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 10:45:22,371 INFO    MainThread:40448 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 10:45:22,372 INFO    MainThread:40448 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 10:45:28,266 INFO    MainThread:40448 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 10:45:28,266 INFO    MainThread:40448 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 10:45:28,266 INFO    MainThread:40448 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 10:45:28,267 INFO    MainThread:40448 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 10:45:28,267 INFO    MainThread:40448 [wandb_init.py:init():847] run started, returning control to user process
2024-03-05 10:45:28,269 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:28,269 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:45:28,281 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:45:28,285 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:28,285 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:45:28,300 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:45:28,305 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:28,305 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:45:29,317 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:45:29,330 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:29,330 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:45:31,801 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:45:31,803 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:31,803 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:45:48,558 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:45:48,563 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:45:48,563 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:47:51,233 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:56:33,386 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:56:33,386 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 10:56:33,437 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 10:56:33,554 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 10:56:33,554 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:22,347 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:22,360 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:22,360 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:22,596 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:22,653 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:22,653 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:22,752 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:22,769 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:22,769 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:22,951 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:22,963 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:22,963 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,123 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,125 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,125 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,280 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,285 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,285 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,453 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,458 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,458 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,601 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,605 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,605 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,783 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,789 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,789 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:23,920 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:23,924 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:23,924 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:24,100 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:24,104 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:24,104 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:24,287 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:24,290 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:24,290 INFO    MainThread:40448 [wandb_init.py:_pause_backend():437] pausing backend
2024-03-05 12:29:24,473 INFO    MainThread:40448 [wandb_init.py:_resume_backend():442] resuming backend
2024-03-05 12:29:24,484 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 12:29:24,484 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Configure stats pid to 40448
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from C:\Users\OJH\.config\wandb\settings
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_122924-5aqzht6a\logs\debug.log
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_122924-5aqzht6a\logs\debug-internal.log
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_init.py:init():566] calling init triggers
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 12:29:24,485 INFO    MainThread:40448 [wandb_init.py:init():591] re-initializing run, found existing run on stack: s57l13nj
2024-03-05 12:29:24,486 INFO    MainThread:40448 [wandb_run.py:_finish():1970] finishing run jonghwan_oh/Model prediction/s57l13nj
2024-03-05 12:29:24,486 INFO    MainThread:40448 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 12:29:24,486 INFO    MainThread:40448 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 12:29:24,486 INFO    MainThread:40448 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 12:29:24,487 INFO    MainThread:40448 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 12:29:24,487 INFO    MainThread:40448 [wandb_run.py:_restore():2193] restore
2024-03-05 12:29:24,487 INFO    MainThread:40448 [wandb_run.py:_restore():2199] restore done
2024-03-05 12:31:50,531 WARNING MsgRouterThr:40448 [router.py:message_loop():77] message_loop has been closed
2024-03-05 12:31:51,291 INFO    MainThread:40448 [wandb_run.py:_restore():2193] restore
2024-03-05 12:31:51,291 INFO    MainThread:40448 [wandb_run.py:_restore():2199] restore done
2024-03-05 12:31:51,542 ERROR   MainThread:40448 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2219, in _atexit_cleanup
    self._on_finish()
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2474, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2436, in _on_probe_exit
    result = handle.wait(timeout=0, release=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 601, in init
    latest_run.finish()
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 1961, in finish
    return self._finish(exit_code, quiet)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 1976, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2230, in _atexit_cleanup
    self._backend.cleanup()
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\backend\backend.py", line 232, in cleanup
    self.interface.join()
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 547, in join
    super().join()
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\interface.py", line 710, in join
    _ = self._communicate_shutdown()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 440, in _communicate_shutdown
    _ = self._communicate(record)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 300, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\OJH\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
